locale: "en-US"
title: Uqbar Data Solutions ~ Juan Manuel Berros
url: "https://jmberros.me" # the base hostname & protocol for your site
baseurl: "" # the subpath of your site, e.g. /blog/
google_analytics_key: ""

# Default description in social shares for the jekyll-seo-tag gem
author:
  name: Juan Manuel Berros
  email: juanma.berros [at] gmail [dot] com

permalink: pretty

plugins:
  - "jekyll-feed"
  - "jekyll-seo-tag"
  - "jekyll-paginate"
  - "jekyll-sitemap"

# Jekyll SEO Tag
webmaster_verifications:
  google: # 1234
  bing: # 1234
  alexa: # 1234
  yandex: # 1234

social_icons:
  - LinkedIn
